### ISSUE TITLE
Error message on successful decrypt

### ISSUE THREAD

**Issue by d1str0** [HackThisCode/CryptoPaste#3] opened 2017-05-25 04:00 UTC
<img width="1437" alt="screen shot 2017-05-24 at 8 55 34 pm" src="https://cloud.githubusercontent.com/assets/3741618/26435425/f3719306-40c3-11e7-9f78-78e51a545a3e.png">

Chrome 58 on macOS.

**Comment by d1str0** [comment] 2017-05-25 04:01
Shouldn't matter but: https://cryptopaste.org/3LZ3Q7bJ 
password: "testpassword"

**Comment by Kage** [comment] 2017-06-01 18:10
I've gotten that error, too, but I'm not sure what the cause is.  Is it due to the scrollToTop thingy?  And if so, why?

**Comment by bnadarevic** [comment] 2017-06-04 12:53
this seems to be chrome only error as it works on firefox. https://stackoverflow.com/questions/41977399/chrome-only-error-failed-to-execute-scroll-on-window-no-function-was-found
You could use window.scrollTo that seems to be supported by more browsers but it seems it doesn't have "smooth" option

**Comment by Kage** [comment] 2017-06-04 21:07
Should be fixed as of de7180d, please verify.

**Comment by bnadarevic** [comment] 2017-06-05 14:06
indeed i don't get error anymore, good job

**Comment by Kage** [comment] 2017-06-07 16:57
Great! Resolved.

**Closed as completed by Kage** 2017-06-07 16:57 UTC
Labels: bug, help wanted
